# Generated by Django 2.1.5 on 2019-02-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('uses', models.TextField()),
                ('growing_period', models.TextField()),
                ('further_info', models.TextField()),
                ('Physiology', models.TextField()),
                ('category', models.TextField()),
                ('temp_abs_min', models.CharField(max_length=3)),
                ('temp_abs_max', models.CharField(max_length=3)),
                ('temp_opt_min', models.CharField(max_length=3)),
                ('temp_opt_max', models.CharField(max_length=3)),
                ('rf_abs_min', models.CharField(max_length=20)),
                ('rf_abs_max', models.CharField(max_length=20)),
                ('rf_opt_min', models.CharField(max_length=20)),
                ('rf_opt_max', models.CharField(max_length=20)),
                ('crop_cycle', models.TextField()),
            ],
        ),
    ]
