# Generated by Django 2.1.5 on 2019-02-24 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='crop',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.Category'),
        ),
    ]
